// <auto-generated />
using System;
using DataFlowRRHH.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataFlowRRHH.Migrations
{
    [DbContext(typeof(BdbioAdminSqlContext))]
    partial class BdbioAdminSqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Latin1_General_CI_AS")
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataFlowRRHH.Models.Department", b =>
                {
                    b.Property<int>("IdDepartment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDepartment"));

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DepartamentosInferiores")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("DepartamentosSuperiores")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("IdParent")
                        .HasColumnType("int");

                    b.Property<string>("SupervisorEmail")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SupervisorName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdDepartment")
                        .HasName("aaaaaDepartment_PK");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("IdDepartment"), false);

                    b.ToTable("Department", (string)null);
                });

            modelBuilder.Entity("DataFlowRRHH.Models.Device", b =>
                {
                    b.Property<int>("IdDevice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDevice"));

                    b.Property<int?>("Attendance")
                        .HasColumnType("int");

                    b.Property<decimal?>("BaudRate")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Comment")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("Connect")
                        .HasColumnType("bit");

                    b.Property<string>("ConnectionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("DownloadRecords")
                        .HasColumnType("bit");

                    b.Property<string>("Ip")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("IP");

                    b.Property<int>("MachineNumber")
                        .HasColumnType("int");

                    b.Property<string>("MachinePassword")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<short?>("PortNumber")
                        .HasColumnType("smallint");

                    b.Property<int?>("SerialPort")
                        .HasColumnType("int");

                    b.Property<bool>("Synchronize")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("IdDevice")
                        .HasName("aaaaaDevice_PK");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("IdDevice"), false);

                    b.ToTable("Device", (string)null);
                });

            modelBuilder.Entity("DataFlowRRHH.Models.Feriado", b =>
                {
                    b.Property<int>("IdException")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdException"));

                    b.Property<DateTime>("BeginingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("EndingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentFactor")
                        .HasColumnType("int");

                    b.Property<bool>("Recurring")
                        .HasColumnType("bit");

                    b.HasKey("IdException")
                        .HasName("aaaaaExceptionStr_PK");

                    b.ToTable("Exception", (string)null);
                });

            modelBuilder.Entity("DataFlowRRHH.Models.Record", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordTime")
                        .HasColumnType("datetime");

                    b.Property<int>("RecordType")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("MachineNumber")
                        .HasColumnType("int");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("VerifyMode")
                        .HasColumnType("int");

                    b.Property<int>("Workcode")
                        .HasColumnType("int");

                    b.HasKey("IdUser", "RecordTime", "RecordType")
                        .HasName("aaaaaRecord_PK");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("IdUser", "RecordTime", "RecordType"), false);

                    b.HasIndex("MachineNumber");

                    b.HasIndex(new[] { "IdUser" }, "RecordIdUser");

                    b.HasIndex(new[] { "IdUser" }, "UserRecord");

                    b.ToTable("Record", (string)null);
                });

            modelBuilder.Entity("DataFlowRRHH.Models.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("CuttingHour")
                        .HasColumnType("int");

                    b.Property<int?>("CuttingMinute")
                        .HasColumnType("int");

                    b.Property<int?>("Cycle")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ShiftId")
                        .HasName("aaaaaShift_PK");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("ShiftId"), false);

                    b.ToTable("Shift", (string)null);
                });

            modelBuilder.Entity("DataFlowRRHH.Models.ShiftDetail", b =>
                {
                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<int>("DayId")
                        .HasColumnType("int");

                    b.Property<int>("AutoRestMinute")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("LeastTimeAutoAssigned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("MinExtraTimeOnBegin")
                        .HasColumnType("int");

                    b.Property<int?>("MinExtraTimeOnEnd")
                        .HasColumnType("int");

                    b.Property<bool?>("PayExtraTimeOnBegin")
                        .HasColumnType("bit");

                    b.Property<bool?>("PayExtraTimeOnEnd")
                        .HasColumnType("bit");

                    b.Property<int>("PayFactExtraTimeOnBegin")
                        .HasColumnType("int");

                    b.Property<int>("PayFactExtraTimeOnEnd")
                        .HasColumnType("int");

                    b.Property<int>("RestType")
                        .HasColumnType("int");

                    b.Property<int>("Rt1max")
                        .HasColumnType("int")
                        .HasColumnName("RT1Max");

                    b.Property<int>("Rt1minute")
                        .HasColumnType("int")
                        .HasColumnName("RT1Minute");

                    b.Property<int>("Rt21beginHour")
                        .HasColumnType("int")
                        .HasColumnName("RT21BeginHour");

                    b.Property<int>("Rt21beginMinute")
                        .HasColumnType("int")
                        .HasColumnName("RT21BeginMinute");

                    b.Property<int>("Rt21endHour")
                        .HasColumnType("int")
                        .HasColumnName("RT21EndHour");

                    b.Property<int>("Rt21endMinute")
                        .HasColumnType("int")
                        .HasColumnName("RT21EndMinute");

                    b.Property<bool>("Rt22")
                        .HasColumnType("bit")
                        .HasColumnName("RT22");

                    b.Property<int>("Rt22beginHour")
                        .HasColumnType("int")
                        .HasColumnName("RT22BeginHour");

                    b.Property<int>("Rt22beginMinute")
                        .HasColumnType("int")
                        .HasColumnName("RT22BeginMinute");

                    b.Property<int>("Rt22endHour")
                        .HasColumnType("int")
                        .HasColumnName("RT22EndHour");

                    b.Property<int>("Rt22endMinute")
                        .HasColumnType("int")
                        .HasColumnName("RT22EndMinute");

                    b.Property<bool>("Rt23")
                        .HasColumnType("bit")
                        .HasColumnName("RT23");

                    b.Property<int>("Rt23beginHour")
                        .HasColumnType("int")
                        .HasColumnName("RT23BeginHour");

                    b.Property<int>("Rt23beginMinute")
                        .HasColumnType("int")
                        .HasColumnName("RT23BeginMinute");

                    b.Property<int>("Rt23endHour")
                        .HasColumnType("int")
                        .HasColumnName("RT23EndHour");

                    b.Property<int>("Rt23endMinute")
                        .HasColumnType("int")
                        .HasColumnName("RT23EndMinute");

                    b.Property<int>("Rt2minOverTime")
                        .HasColumnType("int")
                        .HasColumnName("RT2MinOverTime");

                    b.Property<bool>("Rt2overTime")
                        .HasColumnType("bit")
                        .HasColumnName("RT2OverTime");

                    b.Property<int>("Rt2overTimeFactor")
                        .HasColumnType("int")
                        .HasColumnName("RT2OverTimeFactor");

                    b.Property<bool>("Rt2validateMinOverTime")
                        .HasColumnType("bit")
                        .HasColumnName("RT2ValidateMinOverTime");

                    b.Property<bool>("T1accumulateOverTime")
                        .HasColumnType("bit")
                        .HasColumnName("T1AccumulateOverTime");

                    b.Property<int>("T1attTime")
                        .HasColumnType("int")
                        .HasColumnName("T1AttTime");

                    b.Property<int>("T1minOverTime")
                        .HasColumnType("int")
                        .HasColumnName("T1MinOverTime");

                    b.Property<bool>("T1overTime1")
                        .HasColumnType("bit")
                        .HasColumnName("T1OverTime1");

                    b.Property<int>("T1overTime1Factor")
                        .HasColumnType("int")
                        .HasColumnName("T1OverTime1Factor");

                    b.Property<int>("T1overTime1Minutes")
                        .HasColumnType("int")
                        .HasColumnName("T1OverTime1Minutes");

                    b.Property<bool>("T1overTime2")
                        .HasColumnType("bit")
                        .HasColumnName("T1OverTime2");

                    b.Property<int>("T1overTime2Factor")
                        .HasColumnType("int")
                        .HasColumnName("T1OverTime2Factor");

                    b.Property<int>("T1overTime2Minutes")
                        .HasColumnType("int")
                        .HasColumnName("T1OverTime2Minutes");

                    b.Property<bool>("T1overTime3")
                        .HasColumnType("bit")
                        .HasColumnName("T1OverTime3");

                    b.Property<int>("T1overTime3Factor")
                        .HasColumnType("int")
                        .HasColumnName("T1OverTime3Factor");

                    b.Property<int>("T1overTime3Minutes")
                        .HasColumnType("int")
                        .HasColumnName("T1OverTime3Minutes");

                    b.Property<bool>("T1overTime4")
                        .HasColumnType("bit")
                        .HasColumnName("T1OverTime4");

                    b.Property<int>("T1overTime4Factor")
                        .HasColumnType("int")
                        .HasColumnName("T1OverTime4Factor");

                    b.Property<int>("T1overTime4Minutes")
                        .HasColumnType("int")
                        .HasColumnName("T1OverTime4Minutes");

                    b.Property<bool>("T1overTime5")
                        .HasColumnType("bit")
                        .HasColumnName("T1OverTime5");

                    b.Property<int>("T1overTime5Factor")
                        .HasColumnType("int")
                        .HasColumnName("T1OverTime5Factor");

                    b.Property<int>("T1overTime5Minutes")
                        .HasColumnType("int")
                        .HasColumnName("T1OverTime5Minutes");

                    b.Property<bool>("T1validateMinOverTime")
                        .HasColumnType("bit")
                        .HasColumnName("T1ValidateMinOverTime");

                    b.Property<bool>("T2beginOverTime")
                        .HasColumnType("bit")
                        .HasColumnName("T2BeginOverTime");

                    b.Property<int>("T2beginOverTimeFactor")
                        .HasColumnType("int")
                        .HasColumnName("T2BeginOverTimeFactor");

                    b.Property<int>("T2beginOverTimeHour")
                        .HasColumnType("int")
                        .HasColumnName("T2BeginOverTimeHour");

                    b.Property<int>("T2beginOverTimeMinute")
                        .HasColumnType("int")
                        .HasColumnName("T2BeginOverTimeMinute");

                    b.Property<bool>("T2endOverTime1")
                        .HasColumnType("bit")
                        .HasColumnName("T2EndOverTime1");

                    b.Property<bool>("T2endOverTime2")
                        .HasColumnType("bit")
                        .HasColumnName("T2EndOverTime2");

                    b.Property<bool>("T2endOverTime3")
                        .HasColumnType("bit")
                        .HasColumnName("T2EndOverTime3");

                    b.Property<bool>("T2endOverTime4")
                        .HasColumnType("bit")
                        .HasColumnName("T2EndOverTime4");

                    b.Property<bool>("T2endOverTime5")
                        .HasColumnType("bit")
                        .HasColumnName("T2EndOverTime5");

                    b.Property<int>("T2inHour")
                        .HasColumnType("int")
                        .HasColumnName("T2InHour");

                    b.Property<int>("T2inMinute")
                        .HasColumnType("int")
                        .HasColumnName("T2InMinute");

                    b.Property<int>("T2minBeginOverTime")
                        .HasColumnType("int")
                        .HasColumnName("T2MinBeginOverTime");

                    b.Property<int>("T2minOverTime")
                        .HasColumnType("int")
                        .HasColumnName("T2MinOverTime");

                    b.Property<int>("T2outHour")
                        .HasColumnType("int")
                        .HasColumnName("T2OutHour");

                    b.Property<int>("T2outMinute")
                        .HasColumnType("int")
                        .HasColumnName("T2OutMinute");

                    b.Property<int>("T2overTime1BeginHour")
                        .HasColumnType("int")
                        .HasColumnName("T2OverTime1BeginHour");

                    b.Property<int>("T2overTime1BeginMinute")
                        .HasColumnType("int")
                        .HasColumnName("T2OverTime1BeginMinute");

                    b.Property<int>("T2overTime1EndHour")
                        .HasColumnType("int")
                        .HasColumnName("T2OverTime1EndHour");

                    b.Property<int>("T2overTime1EndMinute")
                        .HasColumnType("int")
                        .HasColumnName("T2OverTime1EndMinute");

                    b.Property<int>("T2overTime1Factor")
                        .HasColumnType("int")
                        .HasColumnName("T2OverTime1Factor");

                    b.Property<int>("T2overTime2BeginHour")
                        .HasColumnType("int")
                        .HasColumnName("T2OverTime2BeginHour");

                    b.Property<int>("T2overTime2BeginMinute")
                        .HasColumnType("int")
                        .HasColumnName("T2OverTime2BeginMinute");

                    b.Property<int>("T2overTime2EndHour")
                        .HasColumnType("int")
                        .HasColumnName("T2OverTime2EndHour");

                    b.Property<int>("T2overTime2EndMinute")
                        .HasColumnType("int")
                        .HasColumnName("T2OverTime2EndMinute");

                    b.Property<int>("T2overTime2Factor")
                        .HasColumnType("int")
                        .HasColumnName("T2OverTime2Factor");

                    b.Property<int>("T2overTime3BeginHour")
                        .HasColumnType("int")
                        .HasColumnName("T2OverTime3BeginHour");

                    b.Property<int>("T2overTime3BeginMinute")
                        .HasColumnType("int")
                        .HasColumnName("T2OverTime3BeginMinute");

                    b.Property<int>("T2overTime3EndHour")
                        .HasColumnType("int")
                        .HasColumnName("T2OverTime3EndHour");

                    b.Property<int>("T2overTime3EndMinute")
                        .HasColumnType("int")
                        .HasColumnName("T2OverTime3EndMinute");

                    b.Property<int>("T2overTime3Factor")
                        .HasColumnType("int")
                        .HasColumnName("T2OverTime3Factor");

                    b.Property<int>("T2overTime4BeginHour")
                        .HasColumnType("int")
                        .HasColumnName("T2OverTime4BeginHour");

                    b.Property<int>("T2overTime4BeginMinute")
                        .HasColumnType("int")
                        .HasColumnName("T2OverTime4BeginMinute");

                    b.Property<int>("T2overTime4EndHour")
                        .HasColumnType("int")
                        .HasColumnName("T2OverTime4EndHour");

                    b.Property<int>("T2overTime4EndMinute")
                        .HasColumnType("int")
                        .HasColumnName("T2OverTime4EndMinute");

                    b.Property<int>("T2overTime4Factor")
                        .HasColumnType("int")
                        .HasColumnName("T2OverTime4Factor");

                    b.Property<int>("T2overTime5BeginHour")
                        .HasColumnType("int")
                        .HasColumnName("T2OverTime5BeginHour");

                    b.Property<int>("T2overTime5BeginMinute")
                        .HasColumnType("int")
                        .HasColumnName("T2OverTime5BeginMinute");

                    b.Property<int>("T2overTime5EndHour")
                        .HasColumnType("int")
                        .HasColumnName("T2OverTime5EndHour");

                    b.Property<int>("T2overTime5EndMinute")
                        .HasColumnType("int")
                        .HasColumnName("T2OverTime5EndMinute");

                    b.Property<int>("T2overTime5Factor")
                        .HasColumnType("int")
                        .HasColumnName("T2OverTime5Factor");

                    b.Property<bool>("T2validateMinBeginOverTime")
                        .HasColumnType("bit")
                        .HasColumnName("T2ValidateMinBeginOverTime");

                    b.Property<bool>("T2validateMinOverTime")
                        .HasColumnType("bit")
                        .HasColumnName("T2ValidateMinOverTime");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<bool?>("ValidateExtraTimeOnBegin")
                        .HasColumnType("bit");

                    b.Property<bool?>("ValidateExtraTimeOnEnd")
                        .HasColumnType("bit");

                    b.HasKey("ShiftId", "DayId")
                        .HasName("aaaaaShiftDetail_PK");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("ShiftId", "DayId"), false);

                    b.HasIndex(new[] { "DayId" }, "DayId");

                    b.ToTable("ShiftDetail", (string)null);
                });

            modelBuilder.Entity("DataFlowRRHH.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<short>("Active")
                        .HasColumnType("smallint");

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("AdministratorType")
                        .HasColumnType("int");

                    b.Property<bool?>("ApplyExceptionPermition")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime");

                    b.Property<string>("Comment")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDatetime")
                        .HasColumnType("datetime");

                    b.Property<string>("DevPassword")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("ExceptionPermitionBegin")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ExceptionPermitionEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<short?>("Gender")
                        .HasColumnType("smallint");

                    b.Property<decimal>("HourSalary")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("IdDepartment")
                        .HasColumnType("int");

                    b.Property<int?>("IdProfile")
                        .HasColumnType("int");

                    b.Property<string>("IdentificationNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("LastRecord")
                        .HasColumnType("datetime");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDatetime")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Picture")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<short?>("PictureOrientation")
                        .HasColumnType("smallint");

                    b.Property<string>("Position")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<short>("PreferredIdLanguage")
                        .HasColumnType("smallint");

                    b.Property<int>("Privilege")
                        .HasColumnType("int");

                    b.Property<string>("ProximityCard")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("SendSms")
                        .HasColumnType("int")
                        .HasColumnName("SendSMS");

                    b.Property<string>("Smsphone")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SMSPhone");

                    b.Property<int?>("TemplateCode")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("UseShift")
                        .HasColumnType("bit");

                    b.HasKey("IdUser")
                        .HasName("aaaaaUser_PK");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("IdUser"), false);

                    b.HasIndex("IdDepartment");

                    b.HasIndex(new[] { "CreatedBy" }, "UserCreatedBy");

                    b.HasIndex(new[] { "ModifiedBy" }, "UserModifiedBy");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("DataFlowRRHH.Models.UserShift", b =>
                {
                    b.Property<int>("UserShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserShiftId"));

                    b.Property<DateTime?>("BeginDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdUser")
                        .HasColumnType("int");

                    b.Property<int?>("ShiftId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("UserShiftId")
                        .HasName("aaaaaUserShift_PK");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("UserShiftId"), false);

                    b.HasIndex("IdUser");

                    b.HasIndex(new[] { "ShiftId" }, "ShiftId");

                    b.HasIndex(new[] { "UserShiftId" }, "UserShiftId");

                    b.ToTable("UserShift", (string)null);
                });

            modelBuilder.Entity("DataFlowRRHH.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Departament")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("DataFlowRRHH.Models.Record", b =>
                {
                    b.HasOne("DataFlowRRHH.Models.User", "IdUserNavigation")
                        .WithMany("Records")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("Record_FK00");

                    b.HasOne("DataFlowRRHH.Models.Device", "IdDeviceNavigation")
                        .WithMany()
                        .HasForeignKey("MachineNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdDeviceNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("DataFlowRRHH.Models.ShiftDetail", b =>
                {
                    b.HasOne("DataFlowRRHH.Models.Shift", null)
                        .WithMany("UserShiftDetailsNavigation")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataFlowRRHH.Models.User", b =>
                {
                    b.HasOne("DataFlowRRHH.Models.Department", "IdDepartmentNavigation")
                        .WithMany()
                        .HasForeignKey("IdDepartment")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdDepartmentNavigation");
                });

            modelBuilder.Entity("DataFlowRRHH.Models.UserShift", b =>
                {
                    b.HasOne("DataFlowRRHH.Models.User", null)
                        .WithMany("UserShiftNavigation")
                        .HasForeignKey("IdUser");

                    b.HasOne("DataFlowRRHH.Models.Shift", "ShiftNavigation")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShiftNavigation");
                });

            modelBuilder.Entity("DataFlowRRHH.Models.Shift", b =>
                {
                    b.Navigation("UserShiftDetailsNavigation");
                });

            modelBuilder.Entity("DataFlowRRHH.Models.User", b =>
                {
                    b.Navigation("Records");

                    b.Navigation("UserShiftNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
